#Message for representing Atlas Behavior States and the position of the valve

#The opsition of Valve


bool GO_
bool STOP_

bool sit_in_the_middle_
bool moce_to_right_
bool step_over_the_hump_
bool sit_in_the_passenger_seat_
bool right_foot_down_
bool move_out_
bool place_hands_
bool left_foot_out_
bool goto_to_stand_
bool left_foot_position_control_
bool right_foot_position_control_
bool left_hand_position_control_
bool right_hand_position_control_
bool pelvis_position_control_
bool left_foot_angle_control_
bool right_foot_angle_control_
bool auto_flatten_left_foot_
bool auto_flatten_right_foot_


uint32 up_
uint32 down_
uint32 right_
uint32 left_
uint32 add_
uint32 minus_